version: "3.9"
services:
  notebook:
    build: .
    volumes:
      - ./src:/mnt/src:rw
    ports:
      - "8888:8888"
    # Will need to set this dynamically
    # https://medium.com/redbubble/running-a-docker-container-as-a-non-root-user-7d2e00f8ee15:
    user: "${CURRENT_USER}"
    working_dir: /mnt/src
    command: jupyter-notebook --notebook-dir=/mnt/src --ip 0.0.0.0 --no-browser

